/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dr_inference_multidimensionalscaling_NativeMDSSingleton */

#ifndef _Included_dr_inference_multidimensionalscaling_NativeMDSSingleton
#define _Included_dr_inference_multidimensionalscaling_NativeMDSSingleton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    initialize
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_initialize
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    updateLocations
 * Signature: (II[D)V
 */
JNIEXPORT void JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_updateLocations
  (JNIEnv *, jobject, jint, jint, jdoubleArray);

/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    getSumOfIncrements
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_getSumOfIncrements
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    storeState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_storeState
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    restoreState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_restoreState
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    acceptState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_acceptState
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    makeDirty
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_makeDirty
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    setPairwiseData
 * Signature: (I[D)V
 */
JNIEXPORT void JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_setPairwiseData
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    setParameters
 * Signature: (I[D)V
 */
JNIEXPORT void JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_setParameters
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    getPairwiseData
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_getPairwiseData
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_multidimensionalscaling_NativeMDSSingleton
 * Method:    getLocationGradient
 * Signature: (I[D)V
 */
JNIEXPORT void JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_getLocationGradient
  (JNIEnv *, jobject, jint, jdoubleArray);

JNIEXPORT jint JNICALL Java_dr_inference_multidimensionalscaling_NativeMDSSingleton_getInternalDimension
        (JNIEnv *, jobject, jint);
#ifdef __cplusplus
}
#endif
#endif
