# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('_mds_rcpp_hello', PACKAGE = 'mds')
}

#' Create MDS engine object
#'
#' Helper function creates MDS engine object with given latent dimension, location count and various
#' implementation details. Called by \code{MassiveMDS::engineInitial()}.
#'
#' @param embeddingDimension Dimension of latent locations.
#' @param locationCount Number of locations and size of distance matrix.
#' @param tbb Number of CPU cores to be used.
#' @param simd For CPU implementation: no SIMD (\code{0}), SSE (\code{1}) or AVX (\code{2}).
#' @param truncation Likelihood includes truncation term? Defaults to \code{TRUE}.
#' @param gpu Which GPU to use? If only 1 available, use \code{gpu=1}. Defaults to \code{0}, no GPU.
#' @param single Set \code{single=1} if your GPU does not accommodate doubles.
#' @return MDS engine object.
#'
#' @export
createEngine <- function(embeddingDimension, locationCount, truncation, tbb, simd, gpu, single) {
    .Call('_mds_createEngine', PACKAGE = 'mds', embeddingDimension, locationCount, truncation, tbb, simd, gpu, single)
}

.setPairwiseData <- function(sexp, data) {
    invisible(.Call('_mds_setPairwiseData', PACKAGE = 'mds', sexp, data))
}

.updateLocations <- function(sexp, locations) {
    invisible(.Call('_mds_updateLocations', PACKAGE = 'mds', sexp, locations))
}

.setPrecision <- function(sexp, precision) {
    invisible(.Call('_mds_setPrecision', PACKAGE = 'mds', sexp, precision))
}

.getLogLikelihoodGradient <- function(sexp, len) {
    .Call('_mds_getLogLikelihoodGradient', PACKAGE = 'mds', sexp, len)
}

.getSumOfIncrements <- function(sexp) {
    .Call('_mds_getSumOfIncrements', PACKAGE = 'mds', sexp)
}

