# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('_mds_rcpp_hello', PACKAGE = 'mds')
}

createEngine <- function(embeddingDimension, locationCount, truncation, threads) {
    .Call('_mds_createEngine', PACKAGE = 'mds', embeddingDimension, locationCount, truncation, threads)
}

.setPairwiseData <- function(sexp, data) {
    invisible(.Call('_mds_setPairwiseData', PACKAGE = 'mds', sexp, data))
}

.updateLocations <- function(sexp, locations) {
    invisible(.Call('_mds_updateLocations', PACKAGE = 'mds', sexp, locations))
}

.setPrecision <- function(sexp, precision) {
    invisible(.Call('_mds_setPrecision', PACKAGE = 'mds', sexp, precision))
}

.getLogLikelihoodGradient <- function(sexp, len) {
    .Call('_mds_getLogLikelihoodGradient', PACKAGE = 'mds', sexp, len)
}

.getSumOfIncrements <- function(sexp) {
    .Call('_mds_getSumOfIncrements', PACKAGE = 'mds', sexp)
}

